### ISSUE TITLE
Autoupdate doesn't work properly

### ISSUE THREAD

**Issue by hansek** [mzomparelli/zVirtualDesktop#57] opened 2017-05-05 11:37 UTC
Sometimes zVD shows me dialog informing about new release (there can be written what is the new version ;) ), but when I click YES button, it shows a small progress bar and then after few seconds update dialog appears again.

Installed zVD is still in original version, nothing change.

Firstly:
![image](https://cloud.githubusercontent.com/assets/378835/25743958/866fc01a-3197-11e7-91b7-ab20a1bf73f5.png)

After Yes click:
![image](https://cloud.githubusercontent.com/assets/378835/25744006/d1e07b02-3197-11e7-9547-279f1d1fdc9b.png)

**Comment by mzomparelli** [comment] 2017-05-05 12:05
I noticed this on one of my machines as well. You'll have to update manually when this happens. I can't see why it's happening.

**Comment by mzomparelli** [comment] 2017-05-05 12:18
I'm pretty sure that Windows or another app is blocking the download, but I'm not sure. Out of my 5 machines I run this on, this only happens on my Surface Pro 4. Do you have any ideas what may be happening? I would happy to fix this if I could figure it out.

**Comment by mzomparelli** [comment] 2017-05-05 13:54
Future prompts will tell you what the new version is and what your current version is.

**Comment by mzomparelli** [comment] 2017-05-05 23:42
When this happens you can use the same URL that the app uses to get the current version.

The below link will always get you the current version.

http://zomp.co/Files.aspx?id=zVDEXE1

This other link is the same link on GitHub that gets you the zip file which will always be the same EXE as the above link.

http://zomp.co/Files.aspx?id=zVD

**Comment by hansek** [comment] 2017-05-06 06:46
I tried run the app as Administrator, but it doesn't help.

I don't have any other idea what can be source of the issue 😞 

Will continue with downloading new versions manually 😉

**Comment by mzomparelli** [comment] 2017-05-06 18:04
It could be that the downloader app needs the admin permissions. I'll test it out soon and report back.

**Comment by mzomparelli** [comment] 2017-05-06 18:58
I just tried this running the downloader as admin and still the same thing. I will continue to investigate, but not a high priority at this time.

**Comment by enumag** [comment] 2017-05-07 05:59
@mzomparelli How can I install the latest version then? Download button in readme is broken as well.

**Comment by mzomparelli** [comment] 2017-05-07 16:12
The download buttons should be working. I just tested. You may also use this link to get the current version.

http://zomp.co/Files.aspx?id=zVDEXE1

**Comment by enumag** [comment] 2017-05-07 16:15
@mzomparelli Oh I see now. The buttons work but the downloaded filename has apostrophes around it and can't be used unless I manually rename it.

**Comment by mzomparelli** [comment] 2017-05-07 16:23
What you mentioned about the apostrophes might be the reason for this open issue. Thanks for the feedback. 
See if this Dropbox link does the  same thing.

https://www.dropbox.com/s/16gysy7xcjmzt9t/zVirtualDesktop.exe?dl=1

**Comment by enumag** [comment] 2017-05-07 16:26
Dropbox link is fine. By the way the problem is probably specific to firefox.

**Comment by mzomparelli** [comment] 2017-05-07 16:27
That helps. Let me try out Firefox.

**Comment by mzomparelli** [comment] 2017-05-07 16:35
I will move this to Dropbox completely as long as this one link works for every new version put out there. I'm testing that now.

**Comment by mzomparelli** [comment] 2017-05-07 16:37
Seems to work still when I overwrite the file with another file. This means I can use Dropbox links instead.

**Comment by mzomparelli** [comment] 2017-05-07 16:46
@hansek  & @enumag please download the newest exe using the link. It will allow your next autoupdate to come from Dropbox.com and this might resolve the issue.

This also means zVD is accessible even when my server is down which is almost never anyway. To get the version number it still has to hit my server. I have no plans of putting my SQL Server in the cloud. In case you're wondering, my server is Windows 2012 Server running in a VirtualBox virtual machine. This is very beneficial because I can move the server to any computer I want in less than 30 minutes.

https://www.dropbox.com/s/16gysy7xcjmzt9t/zVirtualDesktop.exe?dl=1

**Comment by hansek** [comment] 2017-05-08 07:51
@mzomparelli Alright, I already downloaded the latest version. 

I'll confirm auto update is working as next version will be available.

Thanks

**Comment by mzomparelli** [comment] 2017-05-10 01:46
My Surface Pro 4 still can't do the auto-update. Still manual updates for now.

**Comment by hansek** [comment] 2017-05-11 16:59
Same by me, zVD shows notification about version 1.0.49, but auto update don't work.

**Comment by mzomparelli** [comment] 2017-05-11 17:03
I didn't do much to zVD last night and obviously I didn't publish an update. Last night I decided to reset my dev machine and I forgot to backup the code for zVD so we have to revert to the last git version which is like 1.0.20 hahaha. just kidding. I don't lose files. Everything is backed up.

**Comment by mzomparelli** [comment] 2017-07-25 04:45
Version 1.0.63 publishes a new downloader. I don't know if it'll resolve this issue.

**Comment by mzomparelli** [comment] 2017-09-12 03:55
![](https://github.trello.services/images/mini-trello-icon.png) [Updater Bug](https://trello.com/c/zQLAwZAC/9-updater-bug)

**Comment by mzomparelli** [comment] 2017-11-13 05:50
This should be fixed. Let me know if you have any problems after downloading the latest build.

https://zomp.co/files.aspx?id=zvd

**Closed as completed** 2017-11-17 04:15 UTC
Labels: bug, resolved
