### ISSUE TITLE
Tray icon not updating when switching desktops

### ISSUE THREAD

**Issue by ev-dev** [mzomparelli/zVirtualDesktop#285] opened 2021-05-18 13:36 UTC
Recently, the tray icon in taskbar stopped updating properly when switching virtual desktops. If I switch from Desktop 1 to 2 (and back & forth), the icon still shows 1. 

However, I have noticed that if I switch from 1->2 and open/close ZVM settings, the icon does visually update to the correct current Desktop number. 

The tray icon normally updates automatically of course, although at times with a bit of lag understandably, but now I only see it updating with some manual intervention. 

Despite a few attempts at reinstalling, and setting ZVM process priority higher, I've had no luck. Any insight on this issue would be greatly appreciated 🙏 

Ps. thanks again for providing this tool, it's pretty much the only lightweight/functional solution I've found to substitute Window's terribly unresponsive built-in window/desktop manager.

**Comment by mzomparelli** [comment] 2021-05-18 19:49
Thanks for the feedback. I'm sorry to hear about this issue you are experiencing. I have not experienced this issue myself. So far you're the first. Knowing that, it could be something specific with your machine. Maybe a software conflict. I'll do my best to help get to the bottom of it.

Can you tell me your Win10 version and what hotkeys you are using to switch desktops? Also if you could include a list of running processes?

**Comment by OlleHall** [comment] 2021-05-19 22:36
I have the same issue after updating to the latest dev build (21382). Now the icon won't update anymore :(

**Comment by mzomparelli** [comment] 2021-05-20 01:32
Thanks, I have reproduced this issue and I'm looking into it.

**Comment by mzomparelli** [comment] 2021-05-20 01:40
Looks like the `IVirtualDesktopNotification` interface has changed.

Putting this here for reference:

```
[Guid("cd403e52-deed-4c13-b437-b98380f2b1e8")]
interface IVirtualDesktopNotification : IUnknown {
    HRESULT Proc3(/* Stack Offset: 8 */ [In] IObjectArray* p0, /* Stack Offset: 16 */ [In] IVirtualDesktop* p1);
    HRESULT Proc4(/* Stack Offset: 8 */ [In] IObjectArray* p0, /* Stack Offset: 16 */ [In] IVirtualDesktop* p1, /* Stack Offset: 24 */ [In] IVirtualDesktop* p2);
    HRESULT Proc5(/* Stack Offset: 8 */ [In] IObjectArray* p0, /* Stack Offset: 16 */ [In] IVirtualDesktop* p1, /* Stack Offset: 24 */ [In] IVirtualDesktop* p2);
    HRESULT Proc6(/* Stack Offset: 8 */ [In] IObjectArray* p0, /* Stack Offset: 16 */ [In] IVirtualDesktop* p1, /* Stack Offset: 24 */ [In] IVirtualDesktop* p2);
    HRESULT Proc7(/* Stack Offset: 8 */ [In] int p0);
    HRESULT Proc8(/* Stack Offset: 8 */ [In] IObjectArray* p0, /* Stack Offset: 16 */ [In] IVirtualDesktop* p1, /* Stack Offset: 24 */ [In] int p2, /* Stack Offset: 32 */ [In] int p3);
    HRESULT Proc9(/* Stack Offset: 8 */ [In] IVirtualDesktop* p0, /* Stack Offset: 16 */ [In] FC_USER_MARSHAL* p1);
    HRESULT Proc10(/* Stack Offset: 8 */ [In] IApplicationView* p0);
    HRESULT Proc11(/* Stack Offset: 8 */ [In] IObjectArray* p0, /* Stack Offset: 16 */ [In] IVirtualDesktop* p1, /* Stack Offset: 24 */ [In] IVirtualDesktop* p2);
    HRESULT Proc12(/* Stack Offset: 8 */ [In] IVirtualDesktop* p0, /* Stack Offset: 16 */ [In] FC_USER_MARSHAL* p1);
}
```

**Comment by mzomparelli** [comment] 2021-05-20 02:42
This issue is resolved in 1.0.96.4. Please let me know if you have any more issues.

**Closed as completed** 2021-05-20 02:42 UTC
Labels: bug, resolved

**Comment by OlleHall** [comment] 2021-05-20 19:06
> This issue is resolved in 1.0.96.4. Please let me know if you have any more issues.

Where can I download this version?

**Comment by mzomparelli** [comment] 2021-05-20 21:42
Sorry should have mentioned that. On the main website->Simply use the Insider link

https://zvirtualdesktop.com/

![image](https://user-images.githubusercontent.com/10564234/119052545-5eadb580-b98a-11eb-8de4-89f94fe1f3a9.png)

**Comment by mzomparelli** [comment] 2021-05-20 21:44
All builds have been updated, but since you are running insider then you want my insider build :)
