### ISSUE TITLE
Being forced back to old desktop

### ISSUE THREAD

**Issue by ghost** [mzomparelli/zVirtualDesktop#126] opened 2017-11-15 21:46 UTC
The bug happens when I create a window in e.g. desktop 1 and then move it to desktop 2, and then switch to any other desktop (e.g. desktop 2). Once I do this, whenever I try to switch back to desktop 1, it immediately jumps to desktop 2 and always focuses on that specific window. This keeps happening until I close the window. If I create the window in desktop 2 and don't move it, no problems occur.

**Comment by mzomparelli** [comment] 2017-11-15 22:50
This should be fixed now. If you have the Force Update button on the More Settings tab then you can use that to get the updated exe. I'll publish a new version soon, but the exe is fully updated...just haven't incremented the version yet.

EDIT:
Marking as resolved, because it seems to be, but if you still have this issue then I'll remove the tag and continue debugging.

**Comment by nicolasdejong** [comment] 2017-11-16 05:17
Interesting! I had the same, yesterday, a couple of times. I figured it was the buggy Windows implementation of virtual screens. I often have that if I hover over icons in the taskbar, I see previews of windows that are not on the current virtual desktop or notice my mouse pointer changing to a resize pointer for a window that is on a different virtual desktop. Hence: buggy. Wishing that ms fixes this in an updated sometime. Hard to know if any of this has to do with zVirtualDesktop.

Quite annoying though. It simply is impossible to go to that particular vdesktop. Both for going directly to it (e.g. 1 -> 5 -> 1) or indirectly (e.g. 1 -> 2 -> 3 -> 4 -> 5 -> 1) until that window is closed.

I'll force update and see if it happens again.

**Comment by mzomparelli** [comment] 2017-11-17 00:00
Luckily, I've only experienced it once. It wasn't until @amrahman96  described the steps to reproduce that I knew why it was happening. It was due to my code trying to refocus the last window from the desktop you just switched to. I removed all of that code for now and will be working on a better way to do this. Usually my code is decent, but sometimes I look at something and I'm like _why the f**k did I do it this way and why am I not checking such & such first_.

Let me know if you are still having this issue after grabbing a new EXE.

**Closed as completed** 2017-11-20 21:13 UTC
Labels: bug, resolved
