### ISSUE TITLE
Desktop view feedback

### ISSUE THREAD

**Issue by oywino** [mzomparelli/zVirtualDesktop#54] opened 2017-05-04 06:36 UTC
When I activate desktop view, i find that clicking on any window does nothing. But if I right-click, zVD jumps to that particular desktop and app. Is it by design that clicking does nothing (I have to right-click)?

Also, several of my apps is just shown as a white box with nothing inside. And the others that do show, are framed in a white box which is too large 
[img]http://i.imgur.com/ZPQ8GPa.jpg[/img]

**Comment by mzomparelli** [comment] 2017-05-04 11:22
that is by design. left-click and drag while still clicked to move the window. Right click takes you to the window. The metro app sometimes display funny.  I'll look into the issues you see.

**Comment by mzomparelli** [comment] 2017-05-04 12:10
Do you have any software installed that you think might be causing this? If so, what is it?

Does it have anything to do with the size of the actual window? Or maybe something to do with multiple monitors? I use two monitors and it looks good on my PC.

**Comment by mzomparelli** [comment] 2017-05-04 12:37
Looks like I broke the drag and drop feature. I'm working on it because I want to use it today.

**Comment by mzomparelli** [comment] 2017-05-04 12:45
The drag and drop is fixed. Use this link to get a fixed version of 1.0.43. I'll publish this fix as 1.0.44 later this evening.

http://zomp.co/Files.aspx?id=zVDEXE1

**Comment by oywino** [comment] 2017-05-04 13:28
Using the Desktop view just to get an immediate overview of all my current apps and on-goings, is great. I'd like to be able to press the Escape-key to go back to where I came from.
As it is now, I have to make a selection to get out of Desktop View or press the key-combination again. (this is a nice-to-have request)

**Comment by mzomparelli** [comment] 2017-05-04 13:50
I'm glad you like it. I will add the escape key to exit.

**Comment by oywino** [comment] 2017-05-04 14:36
Hi, I screen captured part of the Desktop View (only the two leftmost desktops 4-5), and in the image below, you can see how I think it looks better. In desktop 5 I crossed out the way it looks now, and instead tried to illustrate how I think it should look using Paintshop to edit the screendump.
[img]http://i.imgur.com/Fj9gzBo.jpg[/img]
Please disregard the fuzzyness of the images (Its just because I used pixel scaling). The objective here is to utilize all available space to make its thumb image large enough to actually be able to see what it is. 
As you can see from column 4, it is impossible for me to see what the thumb contains. Also, it seems odd to waste that much space on a white rectangle to the right of each thumb....

**Comment by mzomparelli** [comment] 2017-05-04 15:05
I don't know why you have that white space. Could you identify software that might be causing it?

The width of the thumbnails is auto-adjusted, but I didn't do that for the height. I was thinking of zooming in on the window if you hover or auto-adjust the height.

**Comment by mzomparelli** [comment] 2017-05-04 15:14
How do you have a Gadget on your desktop? I thought Microsoft did away with those. I want it.

**Comment by oywino** [comment] 2017-05-04 17:04
First things first: I stopped all foreground apps. No difference. Then I rebooted and launched only an explorer window. No difference. Same white space.
Then I disabled all autostarting background processes I could think of by disabling them in autostart, and rebooted. No difference. Same white space.
So I have no idea if this is caused by an app, or as a result of something deeper, like a driver perhaps.
My setup is an external Dell monitor connected via Displayport. The Screen resolution is 2560x1440, so highly rectangular.

**Comment by mzomparelli** [comment] 2017-05-04 17:16
So you are just using a single monitor?

**Comment by oywino** [comment] 2017-05-04 17:17
Regarding the Gadgets, this is MS standard Windows gadget packet from windows 7. 
Windows 10 complains a bit during installation, but only then, and not very much. I love these gadgets.
At first, I thought perhaps it was the Gadgets that caused this problem, but disabling it completely made no difference.

**Comment by mzomparelli** [comment] 2017-05-04 17:22
Are your windows maximized? I wonder if this has to do with your high resolution and/or windows not being full screen. I use 1080 resolution and mine looks perfect for all windows maximized, minimized, or just sized smaller than the window space.

**Comment by oywino** [comment] 2017-05-04 17:50
The amount of white space changes with the size of the window, but never goes away completely whether it is maximized, minimized, or just sized smaller than the window space. I use only one monitor (my laptop lid is closed).

**Comment by oywino** [comment] 2017-05-04 17:52
When minimized, the white box is 100% white. the size is always the same.

**Comment by mzomparelli** [comment] 2017-05-04 18:21
Thanks for the info. I'll see what I can figure out. If you obtain any additional info then please keep posting here.

Maybe try something to eliminate a software conflict. I see that you are running VBox. Try running zVirtualDesktop in a fresh Windows 10 VBox and see if you get the same results. Then try installing programs to possibly pin-point the culprit.

**Comment by oywino** [comment] 2017-05-04 18:57
I tried running zVD in VirtualBox. 
Exactly the same result; Big white rectangles. 
The resolution I use in VB is 1600x1200

**Comment by mzomparelli** [comment] 2017-05-04 19:00
This is good info. It leads me to believe it has to do with screen resolution. I will start with testing that,  but it might be difficult since I don't have any monitors that support any higher than 1080. I'll figure something out.

**Comment by oywino** [comment] 2017-05-04 20:14
I tried zVD now on a completely new machine. A Dell i5 laptop using only the internal LCD screen.
Regretfully, the problem is exactly the same.

**Comment by mzomparelli** [comment] 2017-05-04 22:07
What's the resolution the Dell laptop screen?

**Comment by mzomparelli** [comment] 2017-05-04 22:11
Can you try changing the resolution to 1080 to see if that helps?

**Comment by mzomparelli** [comment] 2017-05-05 03:48
So I was just doing the math and your resolution is the normal aspect ratio 16:9 like mine. Your dell laptop screen though is 4:3 ratio. My point is, I don't think it's screen resolution causing this. 

The odd thing is that the Mail app in your screen shot spans the entire thumbnail.

I tested this on my Surface Pro 4 with resolution 2736 x 1824 and it displays as expected. It also displays on my other 4 PCs as expected. What is your Win 10 version?

**Comment by mzomparelli** [comment] 2017-05-05 04:07
Can you open some other windows, like Explorer, Internet Explorer, Edge, Notepad, etc and take a screen shot of that?

**Comment by oywino** [comment] 2017-05-05 11:00
I have tried a number of apps, and they all behave the same wa. This is definitely not an app issue.
None of my laptops offered 1080, but I tried 1024x768 and it was exactly the same.

**Comment by mzomparelli** [comment] 2017-05-05 12:13
I ran zVD on 5 machines and they all display as expected. Since I can't reproduce this issue it is going to be difficult to resolve. Why do you suppose your mail app spanned the entire thumbnail. That leads me to believe that something on your machines is causing it. Maybe it's driver related like you said at first. What is your Windows 10 version?

**Comment by oywino** [comment] 2017-05-05 12:59
It's strange that the mail app actually did span the whole thumbnail. I didn't notice that until you mentioned it. Funny thing is that I'm unable to reproduce that. Now, if I go to zVD Desktop View, my email app only shows as white rectangle. (and so does many other apps as well, but not all).
My windows is always updated. currently 1607, Build 14393.1066

**Comment by mzomparelli** [comment] 2017-05-05 13:35
The all white thumbnail is something happening to the metro apps. I am looking into that, but it is different than the issue of not spanning the entire width. You don't have the current version of Windows, but I don't think that matters.

My WinVer

![image](https://cloud.githubusercontent.com/assets/10564234/25747660/db9a39e6-316d-11e7-83d6-83e92827b0e6.png)

**Comment by oywino** [comment] 2017-05-05 15:11
Hmmm... that's strange. I don't even have an about window that looks anything like the one your'e showing here. If I click "update", I get a message that everything is updated.  How did you produce that window?

**Comment by mzomparelli** [comment] 2017-05-05 16:39
Press WIN+R to open the run dialog and type WinVer there and press enter.

Alternatively, you could open the start menu and begin typing WinVer and it will popup for you to click on and run.

You can go here to get the recent Creators update.

https://www.microsoft.com/en-us/software-download/windows10

**Comment by oywino** [comment] 2017-05-05 18:18
So, I updated to 1703 and now it "works". Meaning that each app "fills" the whole rectangle. But the app thumbnail becomes very distorted as the rectangle is fixed 16/9 and besides, it's so small I am unable to see any detail (unless the app is very colorful)....
Why it works on 1703 and not on 1607 - beats me....

**Comment by mzomparelli** [comment] 2017-05-05 18:32
Very Interesting! These Thumbnails are not specific to Win 10. There were introduced in Windows 7. Can you send another screenshot so I can see the distorting you are referring to? I think I know what it. I just need to auto size the height like I do with the width.

**Comment by oywino** [comment] 2017-05-05 18:37
![image](https://cloud.githubusercontent.com/assets/18447119/25759415/b5c5ff9c-31d2-11e7-84c0-ec78369172b0.png)

**Comment by mzomparelli** [comment] 2017-05-05 18:44
Ok, I can fix this!

I'm going to close this issue, but I will work on fixing the auto height tonight.

**Closed as completed** 2017-05-05 18:45 UTC
Labels: bug

**Comment by mzomparelli** [comment] 2017-05-06 00:47
I'm publishing an update tonight that will maintain the aspect ratio of your primary monitor. 
v1.0.45

**Comment by oywino** [comment] 2017-05-06 06:21
This now looks perfect!
However - you still use right-click to select the app ?  I totally fail to understand why you've decided to deviate from the de-facto standard in this regard. At best, this is confusing...  Please explain why you cannot (will not) use the left-click which is the default Windows standard.

**Comment by mzomparelli** [comment] 2017-05-06 18:07
You are right, it's stupid for me to do this and the reason is even worse. I just didn't feel like handling that along with the mouse down for the dragging capability so instead I just checked which mouse button was pressed. Pure laziness. Consider it corrected in version 1.0.46. I'll probably also have a context menu for thumbnails.

**Comment by oywino** [comment] 2017-05-06 18:45
What can I say - but Thank you ! 🥇 
Your humble attitude earns you a medal...

**Comment by oywino** [comment] 2017-05-10 11:51
After upgrade to 1.0.49 I experience some new "bugs". 
First and foremost that a number of resident background apps are now shown as a series of blank boxes on the "Show on all Desktop" 

![20170510_133253](https://cloud.githubusercontent.com/assets/18447119/25897220/7b59ef54-3587-11e7-8e2e-ab2e4e789359.jpg)

Also, earlier I could use the Win10 built-in Snipper (Screen grabber) to capture part of the zVD All Desktop View, but this is no longer possible so this time I had to use my camera to take a screen-shot.

**Comment by mzomparelli** [comment] 2017-05-10 12:21
Yep, looks like I broke stuff. I'll what i can do about fixing some of it this morning.

**Comment by mzomparelli** [comment] 2017-05-10 12:26
I fixed some of it including the windows you mention in the pinned column. It should not show those now.

https://www.dropbox.com/s/16gysy7xcjmzt9t/zVirtualDesktop.exe?dl=1
