### ISSUE TITLE
No longer open source

### ISSUE THREAD

**Issue by jan-glx** [mzomparelli/zVirtualDesktop#43] opened 2017-04-21 12:21 UTC
I just noticed that zVirtualDesktop is no longer open source. While this is sad for us but of course totally up to you, it is highly discouraged to silently change the license. Please make clear that  zVirtualDesktop is no longer open source (folder in repository suggest otherwise) and no longer free and open source software. Could you maybe explain why you did close your great project? 
For everyone else: my fork https://github.com/jan-glx/zVirtualDesktop contains the last version licensed under the MIT license, but will not be developed further by me.

**Comment by mzomparelli** [comment] 2017-04-21 14:19
I've added many things since I closed the source. You can still see my source using a .NET decompiler because I'm not doing any obfuscation at the moment. This app is still free for personal use and is also free to use at your work. You may not distribute my newer versions at work, but you may distribute outside of work. People can use your fork, but they lose new features and bug fixes and also support from me. I have been considering open source again. I'm sorry if I upset you with this change.

The reason I closed this was because at the moment I wanted to be the only one updating. I do not want different version being used until I am happy with the end product. Since I'm still making changes and I want the user to have the best possible experience I closed the source to avoid users getting someone's old non-maintained version. I will open it back up when I'm happy with the product and I'm done making significant changes.

**Comment by mzomparelli** [comment] 2017-04-21 22:35
I was also kind of hoping that I would get some donations because I think this is a useful utility and I am spending my free time putting it together, maintaining it, and releasing it for everyone to use. I encourage everyone that finds this utility useful to reach into their pocket and send me a few dollars. Just a little something to say thanks for making this tool for us and continuing to improve it. I listen to all feedback and I'm trying to make this a tool that everyone loves having on their PC.

**Comment by mzomparelli** [comment] 2017-04-22 00:07
Free .NET Decompiler

https://www.jetbrains.com/decompiler/download/download-thanks.html?platform=windowsWeb

**Comment by jan-glx** [comment] 2017-04-23 11:23
Thank you for your answer, others might have just closed the issue! Some comments on it:
- I cannot image it to be hard to hide something from a decompiler.
- If the source is accessible anyway, why not provide it in the first place?
- I understand your wish to have complete control over the project to be able to make fundamental changes until you found a good program design but I am sure making this point in a [how-to-contribute-page](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) would suffice to stop people from forking and pull requesting.
- But notice that in the current situation the chances of 'users getting someone's old non-maintained version' are much higher; i.e. if you stop working on it, nobody can continue your work b.c. of the licence.
This stops me and potentially others from investing into the project, by using it, reporting issues and proposing changes or even financially.
- Please also consider if people are willing to pay more for the nice but not essential functionality your tool provides (shareware) or in appreciation of your work for mankind (or the subset of frustrated windows 10 virtual desktop users) (free and open source software) ... 

In any case, keep up the good work!

**Comment by mzomparelli** [comment] 2017-04-23 17:04
You make good points here and the feedback is always appreciated. I'm going to take the time to respond to every point you made.

- .NET compiles into MSIL and meta details are still present if you don't perform any obfuscation or packing. This means that any .NET decompiler can present to you the actual source that I wrote. I confirmed this JetBrains dotPeek.

- The license in version 1.0.40 allows you to modify the source via a decompiler and even recompile the modified source for your own use. You are not allowed to redistribute a modified compilation. Using this licensing in conjunction with me providing a hash of my version can help protect users from someone adding malicious code into this application. It's too easy to add a few lines of code to this application to make it log keys and this would go unnoticed by the users. By limiting the ability to fork or redistribute a modified version I'm ensuring the user is not running a keylogger. By using a version directly from my site (which I will add the hash for) you can be sure that you have a non-malicious executable. I don't think I would get malicious versions from github and I am considering putting it back on github.

- Thanks for the tip on "how-to-contribute-page". I did not think of doing this. 

- As for someone getting an old un-maintained version when I stop working on it. I hope that the changes I have made since prevent anyone from even considering an old version. I will, without a doubt, open up the code and change the licensing when I decide to stop maintaining.

- I hope the previous point and my active support of the project help you to continue to invest in its growth. All feedback is welcome.

- I'm not sure what to say about the last point. I made this app for myself just so I could actually use the virtual desktops. Without this tool I refused to use virtual desktops because it was not easy enough to switch and move windows. It just added too many steps which made the entire thing pointless. So for me, this app is an absolute essential. I put it out here because I knew there were others like me.

**Comment by mzomparelli** [comment] 2017-04-23 17:28
I personally would have paid for a tool like mine. I made a point on March 8th about paying for an app that implements hotkeys. 

https://github.com/Eun/MoveToDesktop/issues/42

Everyone has one where you can use AHK. I love AHK, but my app allowed me to uninstall it now that I can create hotkeys for other things in zVirtualDesktop.

If you would have made an app like zVirtualDesktop then I would have donated at least $10 to you because I would be using it every day.

**Closed as completed** 2017-05-03 03:42 UTC
