### ISSUE TITLE
No notification of failed update

### ISSUE THREAD

**Issue by buchmiller** [mzomparelli/zVirtualDesktop#65] opened 2017-05-10 14:25 UTC
I clicked "Yes" to update from version 1.0.48 to 1.0.49. The window closed and nothing happened.
The reason is that my employer blocks all access to dropbox. I'm still able to download the latest version from your website, but it would be nice to know that the update failed with an error message. Maybe it could even be smart enough to attempt the download from a different domain.

**Comment by mzomparelli** [comment] 2017-05-10 15:55
Thanks for the feedback. I will investigate this evening.

**Comment by mzomparelli** [comment] 2017-09-12 03:56
![](https://github.trello.services/images/mini-trello-icon.png) [Updater Bug](https://trello.com/c/zQLAwZAC/9-updater-bug)

**Comment by mzomparelli** [comment] 2017-10-11 00:13
Closing this as it's basically a duplicate of #57

**Closed as completed by mzomparelli** 2017-10-11 00:13 UTC
Labels: bug
